import React, { useState } from "react";
import styled from "styled-components";

const PageHeader = styled.div`
  background: linear-gradient(
    135deg,
    var(--primary-color) 0%,
    var(--secondary-color) 100%
  );
  color: white;
  padding: 8rem 0 4rem;
  text-align: center;
`;

const PageTitle = styled.h1`
  font-size: 3rem;
  font-weight: 700;
  margin-bottom: 1rem;
`;

const PageSubtitle = styled.p`
  font-size: 1.25rem;
  opacity: 0.9;
  max-width: 600px;
  margin: 0 auto;
`;

const Section = styled.section`
  padding: 6rem 0;
`;

const Container = styled.div`
  max-width: 1400px;
  margin: 0 auto;
  padding: 0 2rem;
`;

const FAQGrid = styled.div`
  max-width: 800px;
  margin: 0 auto;
`;

const FAQItem = styled.div`
  border: 1px solid var(--border-color);
  border-radius: 1rem;
  margin-bottom: 1rem;
  overflow: hidden;
`;

const FAQQuestion = styled.button<{ $isOpen: boolean }>`
  width: 100%;
  padding: 1.5rem;
  background: var(--bg-primary);
  border: none;
  text-align: left;
  font-size: 1.125rem;
  font-weight: 600;
  color: var(--text-primary);
  cursor: pointer;
  display: flex;
  justify-content: space-between;
  align-items: center;
  transition: all 0.3s ease;

  &:hover {
    background: var(--bg-accent);
  }

  &::after {
    content: "${(props) => (props.$isOpen ? "−" : "+")}";
    font-size: 1.5rem;
    color: var(--primary-color);
  }
`;

const FAQAnswer = styled.div<{ $isOpen: boolean }>`
  padding: ${(props) => (props.$isOpen ? "1.5rem" : "0 1.5rem")};
  max-height: ${(props) => (props.$isOpen ? "500px" : "0")};
  overflow: hidden;
  transition: all 0.3s ease;
  background: var(--bg-primary);
  color: var(--text-secondary);
  line-height: 1.6;
`;

const FAQ: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const faqs = [
    {
      question: "What is Bind?",
      answer:
        "Bind is an AI-powered publishing platform that helps authors create, edit, and publish their books. We combine cutting-edge artificial intelligence with human creativity to revolutionize the publishing process.",
    },
    {
      question: "How does the AI writing assistant work?",
      answer:
        "Our AI writing assistant uses advanced natural language processing to help you generate content, suggest improvements, and enhance your writing. It can help with everything from brainstorming ideas to polishing your final draft.",
    },
    {
      question: "Is the content generated by AI?",
      answer:
        "While our AI can help generate content, the final work is always a collaboration between the AI and the human author. You maintain full creative control and can edit, modify, or reject any AI suggestions.",
    },
    {
      question: "What types of books can I create with Bind?",
      answer:
        "You can create virtually any type of book with Bind, including novels, non-fiction, children's books, poetry, and more. Our platform is designed to be flexible and adapt to your specific needs.",
    },
    {
      question: "How much does it cost to use Bind?",
      answer:
        "We offer various pricing plans to suit different needs. Our basic plan is free, while premium features are available through our subscription plans. Contact us for detailed pricing information.",
    },
    {
      question: "Can I publish my book traditionally after using Bind?",
      answer:
        "Yes! Books created with Bind can be published through traditional publishing houses or self-published. We provide all the necessary tools and formats for both publishing paths.",
    },
    {
      question: "Is my work protected when using Bind?",
      answer:
        "Absolutely. We take intellectual property rights very seriously. You retain all rights to your work, and our platform includes robust security measures to protect your content.",
    },
    {
      question: "Do I need technical skills to use Bind?",
      answer:
        "No technical skills are required. Our platform is designed to be user-friendly and intuitive. If you can use a word processor, you can use Bind.",
    },
  ];

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <>
      <PageHeader>
        <PageTitle>Frequently Asked Questions</PageTitle>
        <PageSubtitle>
          Find answers to common questions about Bind and AI-powered publishing
        </PageSubtitle>
      </PageHeader>

      <Section>
        <Container>
          <FAQGrid>
            {faqs.map((faq, index) => (
              <FAQItem key={index}>
                <FAQQuestion
                  $isOpen={openIndex === index}
                  onClick={() => toggleFAQ(index)}
                >
                  {faq.question}
                </FAQQuestion>
                <FAQAnswer $isOpen={openIndex === index}>
                  {faq.answer}
                </FAQAnswer>
              </FAQItem>
            ))}
          </FAQGrid>
        </Container>
      </Section>
    </>
  );
};

export default FAQ;
